# Generated by Django 2.0.5 on 2018-05-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('last_commit', models.DateTimeField()),
                ('commits_url', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Organization')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repositories',
                'db_table': 'repository',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['login'], name='organizatio_login_4f8999_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['name'], name='repository_name_41b469_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['created_at'], name='repository_created_708bff_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['last_commit'], name='repository_last_co_db8848_idx'),
        ),
    ]
